/** Sugestões de tipo de serviço para anúncios de Indicação */
export const INDICATION_SERVICE_TYPE_SUGGESTIONS = [
  "Encanador",
  "Eletricista",
  "Pintor",
  "Marceneiro",
  "Pedreiro",
  "Vidraceiro",
  "Ar condicionado",
  "Limpeza",
  "Diarista",
  "Cuidador de idosos",
  "Babá",
  "Buffet",
  "Confeiteiro",
  "Professor particular",
  "Personal trainer",
  "Nutricionista",
  "Psicólogo",
  "Dentista",
  "Veterinário",
  "Adestrador",
  "Motorista",
  "Carreta / Mudança",
  "Manutenção geral",
  "Jardineiro",
  "Dedetização",
  "Outro",
] as const;
